version: '3.1'

services:
  db:
    container_name: sagra_db
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: sagra
      POSTGRES_PASSWORD: sagra
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./postgres/docker-entrypoint-initdb/:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
